### ISSUE TITLE
vignette missing

### ISSUE THREAD

**Issue by ggrothendieck** [mikldk/ryacas0#1]
The vignette is missing.

**Comment by mikldk** [comment]
Which one? These are included: <https://mikldk.github.io/ryacas0/articles/>.

**Comment by ggrothendieck** [comment]
There used to be a single vignette that you could just search through to find cookbook style answers which was very convenient.

**Comment by mikldk** [comment]
I believe <https://mikldk.github.io/ryacas0/articles/elaborate-reference.html> is the single vignette you are referring to?

If you install the package with this command the vignettes are included
```
devtools::install_github("mikldk/ryacas0", 
                         build_opts = c("--no-resave-data", "--no-manual"))
```

I have updated README. I hope it is easier to understand now?

**Comment by ggrothendieck** [comment]
Why the complication which just makes it more difficult to install?  Why can't it just be like nearly every other package in this respect?

**Comment by mikldk** [comment]
My understanding is that such legacy packages cannot be put on CRAN. But I'll try to ask them just to be sure.

**Comment by ggrothendieck** [comment]
It should not be necessary to specify build_opts.  It should build with vignettes without specifying anything.

**Comment by mikldk** [comment]
This package is now on CRAN: <https://CRAN.R-project.org/package=Ryacas0>. I believe this should solve the problems.
